nome = input("digite seu nome ")

print(nome)


numero1 = float(input("digite um numero :"))
numero2  = float(input("digite outro numero :"))


soma = numero1 + numero2 
print(soma)


print("IMC")


peso = float(input("DIGITE SEU PESO : "))
altura = float(input("DIGITE SEU ALTURA : "))
IMC = peso/altura**2

print("IMC" , IMC )

print('SINAIS DE CALCULO ARITMÉTICO')



print(10+200) # soma
print(10-200) # subtração
print(10*200) # multiplicalçi
print(10/200) # divisão
print('modulo', 10%200) #módulo
print(10**2) # potencia
print(10//200.0) # divisão c/ 2 barras


print(10==200) # soma
print(10>200) # subtração
print(10<200) # multiplicalçi
print(10>=200) # divisão
print(10<=200) #módulo
print(10!=2) # potencia


print('SINAIS DE CALCULO ARITMÉTICO')



print(10+200) # soma
print(10-200) # subtração
print(10*200) # multiplicalçi
print(10/200) # divisão
print('modulo', 10%200) #módulo
print(10**2) # potencia
print(10//200.0) # divisão c/ 2 barras


# variáveis -  estruturas de dados 
# funções  - print() input() float() int()
# sinais aritmétivos 



# sinais lógicos


print(10 == 200) # comparar
print(10 > 200) # verifa se 1º numero é maior
print(10<200) # verifa se 1º numero é menor
print(10>=200) # maior ou iguael
print(10<=200) # menor ou igual
print(10 != 2) # diferente